### ISSUE TITLE
idea2021.1插件使用异常

### ISSUE THREAD

**Issue by liuyandeng** [kings1990/fast-request-doc#2]
![1111](https://user-images.githubusercontent.com/19473507/126065633-7fb7bb49-228d-43a3-a6a5-b039ccdb297c.png)

![111](https://user-images.githubusercontent.com/19473507/126065762-d16ce680-171d-48fa-bf72-388516a1efe0.png)

`java.lang.StackOverflowError
	at java.base/java.text.DateFormatSymbols.initializeData(DateFormatSymbols.java:725)
	at java.base/java.text.DateFormatSymbols.<init>(DateFormatSymbols.java:151)
	at java.base/sun.util.locale.provider.DateFormatSymbolsProviderImpl.getInstance(DateFormatSymbolsProviderImpl.java:85)
	at java.base/java.text.DateFormatSymbols.getProviderInstance(DateFormatSymbols.java:370)
	at java.base/java.text.DateFormatSymbols.getInstance(DateFormatSymbols.java:346)
	at java.base/java.util.Calendar.getDisplayName(Calendar.java:2142)
	at java.base/java.text.SimpleDateFormat.subFormat(SimpleDateFormat.java:1156)
	at java.base/java.text.SimpleDateFormat.format(SimpleDateFormat.java:997)
	at java.base/java.text.SimpleDateFormat.format(SimpleDateFormat.java:967)
	at java.base/java.text.DateFormat.format(DateFormat.java:374)
	at io.github.kings1990.plugin.fastrequest.util.KV.getFields(KV.java:64)
	at io.github.kings1990.plugin.fastrequest.util.KV.getFields(KV.java:200)
	at io.github.kings1990.plugin.fastrequest.util.KV.getFields(KV.java:200)
        ...`

使用的是@Controller/@ResponseBody/@RequestMapping组合

**Comment by kings1990** [comment]
你的类被设计成了无限嵌套类，无法解析
